/**
 * Field Helper Text Library
 * Contains descriptive tooltips for all calculator input fields
 */

export const FIELD_HELPERS = {
  // ===== MORTGAGE CALCULATOR =====
  loanAmount: 'The total amount of money you need to borrow for the property purchase',
  interestRate: 'Annual percentage rate (APR) on the loan. Check with your lender for current rates',
  loanTerm: 'Length of the loan repayment period in years. Common terms: 15, 20, or 30 years',
  originationFeePercent: 'One-time fee charged by the lender for processing and originating the loan, as a percentage of the loan amount',
  propertyTaxRate: 'Annual property tax as a percentage of the loan amount. Varies by location',
  homeInsuranceAnnual: 'Annual insurance cost for property protection. Get quotes from multiple insurers',
  pmiRequired: 'Private Mortgage Insurance required when down payment is less than 20% of purchase price',
  pmiRate: 'PMI rate as an annual percentage of the loan amount. Typical range: 0.3-1.5%',
  hoaFeesMonthly: 'Monthly fees for homeowners association. Only applicable if property is in an HOA',
  
  // ===== CAP RATE CALCULATOR =====
  propertyValue: 'Total market value or purchase price of the property',
  annualNOI: 'Net Operating Income - Annual rental revenue minus all operating expenses (not including debt service)',
  capRate: 'Capitalization rate - the annual return on the property based on NOI and value',
  
  // ===== RENTAL ROI CALCULATOR =====
  monthlyRentalIncome: 'Expected monthly rental revenue from tenants. Based on market rates for similar properties',
  monthlyExpenses: 'Monthly operating costs including maintenance, utilities, property taxes, and insurance',
  vacancyRate: 'Percentage of time the property is expected to be vacant and generating no rental income',
  
  // ===== DEVELOPMENT FEASIBILITY =====
  landSize: 'Total land area available for development in square meters',
  costPerM2: 'Construction cost per square meter. Includes labor, materials, and overhead',
  numVillas: 'Total number of villa units planned in the development project',
  developmentCost: 'Total estimated cost for development including construction, permits, and infrastructure',
  launchPrice: 'Expected selling price per unit at market launch',
  
  // ===== IRR CALCULATOR =====
  initialInvestment: 'The amount of capital invested at the beginning (typically a negative number)',
  annualCashFlows: 'Annual net cash flows generated by the investment over its lifetime',
  irr: 'Internal Rate of Return - the discount rate where NPV equals zero',
  
  // ===== NPV CALCULATOR =====
  discountRate: 'The rate used to calculate the present value of future cash flows. Typically the cost of capital or required return rate',
  npv: 'Net Present Value - the sum of all present-valued cash flows. Positive NPV indicates a good investment',
  
  // ===== XIRR CALCULATOR =====
  transactionDates: 'Dates when cash flows occur. Must be in chronological order',
  transactionAmounts: 'Cash flow amounts for each transaction. Negative for outflows, positive for inflows',
  xirr: 'Extended Internal Rate of Return - IRR calculated for irregular cash flow dates',
  
  // ===== CASH FLOW PROJECTOR =====
  projectionYears: 'Number of years to project cash flows into the future',
  initialCashFlow: 'Starting annual cash flow value as the base for projections',
  growthRate: 'Expected annual percentage growth rate of cash flows',
  
  // ===== COMMON FIELDS =====
  currency: 'Select the currency for all monetary values in this calculation',
  year: 'Specific year or year number in the projection or analysis',
  month: 'Month for which you want to calculate or display values',
  strategy: 'Investment strategy or approach for the property or development',
  showAdvanced: 'Toggle to show advanced options and additional configuration fields',
  roi: 'Return On Investment - the percentage profit relative to the total investment',
  cashFlow: 'Annual net cash generated after all expenses and debt payments',
  breakEven: 'Time in months until cumulative cash flow turns positive',
  maintenanceReserve: 'Annual budget reserved for maintenance as a percentage of NOI or revenue',
  reinvestmentRate: 'Expected return rate on reinvested cash flows',
  
  // ===== FINANCIAL METRICS =====
  downPayment: 'Initial payment made at purchase. Typically 10-20% of property value',
  totalInvestment: 'Sum of all capital invested including down payment and closing costs',
  projectedRevenue: 'Total expected revenue over the investment period',
  totalExpenses: 'Sum of all expenses including operating costs and debt service',
  profitMargin: 'Percentage of revenue remaining as profit after all expenses',
  debtServiceCoverage: 'Ratio of NOI to annual debt payment. Higher is better (minimum 1.25x)',
} as const;

/**
 * Get helper text for a specific field
 * @param fieldName - The field name key
 * @returns Helper text or empty string if not found
 */
export function getFieldHelper(fieldName: keyof typeof FIELD_HELPERS): string {
  return FIELD_HELPERS[fieldName] || '';
}

/**
 * Unit labels for common field types
 */
export const FIELD_UNITS = {
  percentage: '%',
  currency: '$', // Use with currency context
  currencyIdr: 'Rp',
  currencyAud: 'A$',
  currencyEur: '€',
  years: 'years',
  months: 'months',
  area: 'm²',
  perSquareMeter: '/m²',
  decimal: '',
  percentage_annual: '%/year',
} as const;

/**
 * Placeholder values for common field types
 */
export const FIELD_PLACEHOLDERS = {
  loanAmount: '500,000,000',
  interestRate: '6.5',
  loanTerm: '20',
  propertyValue: '1,000,000,000',
  annualNOI: '100,000,000',
  monthlyRentalIncome: '5,000,000',
  monthlyExpenses: '500,000',
  vacancyRate: '5',
  landSize: '1000',
  costPerM2: '5000000',
  numVillas: '10',
  discountRate: '10',
  growthRate: '5',
  cashFlow: '50,000,000',
} as const;
