export const config = {
  runtime: 'edge',
};

// Simple in-memory rate limiter for edge runtime
const rateLimitStore = new Map<string, { count: number; resetTime: number }>();

function checkRateLimit(ip: string): { allowed: boolean; remaining: number } {
  const now = Date.now();
  const windowMs = 60 * 1000; // 1 minute
  const maxRequests = 10; // 10 requests per minute

  const entry = rateLimitStore.get(ip);

  if (!entry || entry.resetTime < now) {
    rateLimitStore.set(ip, { count: 1, resetTime: now + windowMs });
    return { allowed: true, remaining: maxRequests - 1 };
  }

  if (entry.count >= maxRequests) {
    return { allowed: false, remaining: 0 };
  }

  entry.count++;
  return { allowed: true, remaining: maxRequests - entry.count };
}

// Security headers for all responses
const securityHeaders = {
  'Content-Type': 'application/json',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
};

export default async function handler(request: Request) {
  if (request.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: securityHeaders,
    });
  }

  // Rate limiting
  const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ||
                   request.headers.get('x-real-ip') ||
                   'unknown';

  const rateCheck = checkRateLimit(clientIp);
  if (!rateCheck.allowed) {
    return new Response(JSON.stringify({ error: 'Too many requests. Please try again later.' }), {
      status: 429,
      headers: {
        ...securityHeaders,
        'Retry-After': '60',
        'X-RateLimit-Remaining': '0',
      },
    });
  }

  const apiToken = process.env.POSTMARK_API_TOKEN;

  if (!apiToken) {
    console.error('POSTMARK_API_TOKEN environment variable is not set');
    return new Response(JSON.stringify({ error: 'Email service not configured. Please set POSTMARK_API_TOKEN in Vercel environment variables.' }), {
      status: 500,
      headers: securityHeaders,
    });
  }

  try {
    const { email, pdfBase64, fileName, reportType } = await request.json();

    if (!email || !pdfBase64 || !fileName) {
      return new Response(JSON.stringify({ error: 'Missing required fields' }), {
        status: 400,
        headers: securityHeaders,
      });
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email) || email.length > 254) {
      return new Response(JSON.stringify({ error: 'Invalid email address' }), {
        status: 400,
        headers: securityHeaders,
      });
    }

    // Validate filename (prevent path traversal)
    if (fileName.includes('..') || fileName.includes('/') || fileName.includes('\\')) {
      return new Response(JSON.stringify({ error: 'Invalid filename' }), {
        status: 400,
        headers: securityHeaders,
      });
    }

    const fromAddress = process.env.POSTMARK_FROM_EMAIL || 'reports@investlandgroup.com';

    const response = await fetch('https://api.postmarkapp.com/email', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-Postmark-Server-Token': apiToken,
      },
      body: JSON.stringify({
        From: fromAddress,
        To: email,
        Subject: `Your ${reportType || 'Investment'} Report - ROI Calculate`,
        HtmlBody: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px;">
            <div style="text-align: center; margin-bottom: 32px;">
              <h1 style="color: #0f172a; font-size: 24px; margin-bottom: 8px;">Your Investment Report</h1>
              <p style="color: #64748b; font-size: 14px;">ROI Calculate - Property Investment Tools</p>
            </div>
            <div style="background: #f8fafc; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
              <p style="color: #334155; font-size: 15px; line-height: 1.6; margin: 0;">
                Your <strong>${reportType || 'Investment'}</strong> report is attached to this email as a PDF.
              </p>
            </div>
            <p style="color: #94a3b8; font-size: 12px; text-align: center;">
              Generated by ROI Calculate &mdash; Professional Property Investment Analysis
            </p>
          </div>
        `,
        Attachments: [
          {
            Name: fileName,
            Content: pdfBase64,
            ContentType: 'application/pdf',
          },
        ],
      }),
    });

    const data = await response.json();

    if (response.ok) {
      return new Response(JSON.stringify({ success: true, id: data.MessageID }), {
        status: 200,
        headers: securityHeaders,
      });
    } else {
      console.error('Postmark error:', data);
      // Return Postmark error details for debugging
      const errorMessage = data.Message || data.ErrorCode || 'Failed to send email';
      return new Response(JSON.stringify({
        error: errorMessage,
        errorCode: data.ErrorCode,
        details: data.Message
      }), {
        status: 500,
        headers: securityHeaders,
      });
    }
  } catch (err) {
    console.error('Email API error:', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: securityHeaders,
    });
  }
}
