export const config = {
  runtime: 'edge',
};

export default async function handler(request: Request) {
  if (request.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  const apiToken = process.env.POSTMARK_API_TOKEN || 'afe358ea-c1ad-48fa-96f0-fdd0e7c3ec26';

  try {
    const { email, pdfBase64, fileName, reportType } = await request.json();

    if (!email || !pdfBase64 || !fileName) {
      return new Response(JSON.stringify({ error: 'Missing required fields' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    const fromAddress = process.env.POSTMARK_FROM_EMAIL || 'reports@investlandgroup.com';

    const response = await fetch('https://api.postmarkapp.com/email', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-Postmark-Server-Token': apiToken,
      },
      body: JSON.stringify({
        From: fromAddress,
        To: email,
        Subject: `Your ${reportType || 'Investment'} Report - ROI Calculate`,
        HtmlBody: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px;">
            <div style="text-align: center; margin-bottom: 32px;">
              <h1 style="color: #0f172a; font-size: 24px; margin-bottom: 8px;">Your Investment Report</h1>
              <p style="color: #64748b; font-size: 14px;">ROI Calculate - Property Investment Tools</p>
            </div>
            <div style="background: #f8fafc; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
              <p style="color: #334155; font-size: 15px; line-height: 1.6; margin: 0;">
                Your <strong>${reportType || 'Investment'}</strong> report is attached to this email as a PDF.
              </p>
            </div>
            <p style="color: #94a3b8; font-size: 12px; text-align: center;">
              Generated by ROI Calculate &mdash; Professional Property Investment Analysis
            </p>
          </div>
        `,
        Attachments: [
          {
            Name: fileName,
            Content: pdfBase64,
            ContentType: 'application/pdf',
          },
        ],
      }),
    });

    const data = await response.json();

    if (response.ok) {
      return new Response(JSON.stringify({ success: true, id: data.MessageID }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      });
    } else {
      return new Response(JSON.stringify({ error: 'Failed to send email', details: data }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      });
    }
  } catch (err) {
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}
